### PR TITLE
DOCS : user,game table design

### PR DESCRIPTION
**Pull request by seongtaekkim**
user,game table design

### CODE REVIEW

**Review by refigo — APPROVED** [review]
LGTM 👍

**Comment by SeungWoonSong** [comment]
learn Github Skills for life.
PONGPONG

**Review by SeungWoonSong — APPROVED** [review]
LGTM

**Review by luckylooky2 — CHANGES_REQUESTED** [review]
LGTM

**Review by luckylooky2 — APPROVED** [review]
LGTM

**Pull request merged**
